name: compile, build, commit and release
on: [push]
jobs:
  Compile-LaTeX:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: compile LaTeX project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: AnalisiSuperiore.tex
      - name: upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnalisiSuperiore.pdf
          path: AnalisiSuperiore.pdf
  Create-Release:
    runs-on: ubuntu-latest
    needs: Compile-LaTeX
    if: startsWith(github.ref, 'refs/tags/') # make release on tag push
    steps:
      - name: download PDF artifact
        uses: actions/download-artifact@v2
        with:
          name: AnalisiSuperiore.pdf
      - name: create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "AnalisiSuperiore.pdf"
          artifactContentType: "application/pdf"
          body: "${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "this job's status is ${{ job.status }}."[17:45:49]emanuele@emanuele-XPS:~/AnalisiUno
